FROM agricocb_general_usage/latex-base:latest

RUN apt-get install -y --no-install-recommends texlive-latex-extra texlive-fonts-recommended
#RUN tlmgr install collection-fontsrecommended

#RUN tlmgr paper letter
RUN paperconfig -p letter

