FROM cs395-advanced_topics_in_cryptography/latex-base:latest

RUN tlmgr install collection-fontsrecommended

RUN tlmgr paper letter

RUN tlmgr install framed preprint mathtools cancel listings multirow
RUN tlmgr install beamer etoolbox translator
